// import { IResource } from "@/typings/course";

// export const mockResources: IResource[] = [
//   {
//     id: 1,
//     title: "Introduction to STEAM Education",
//     description:
//       "An overview of STEAM education principles and their application in the classroom.",
//     link: "https://www.steameducation.org/intro-to-steam",
//     level: 1,
//     type: "Article",
//     createdBy: {
//       email: "emily.carter@example.com",
//       avatar: "https://i.pravatar.cc/300?img=5",
//       username: "Dr. Emily Carter",
//       city: "Boston",
//       id: 1,
//       name: "Emily Carter",
//       jobTitle: "STEAM Curriculum Developer",
//       country: "USA",
//       level: 5,
//     },
//     createdAt: new Date("2024-01-10"),
//     tags: ["STEAM", "Education", "Introduction"],
//   },
//   {
//     id: 2,
//     title: "Growth Mindset in Education",
//     description:
//       "A comprehensive guide on how to cultivate a growth mindset among students.",
//     link: "https://www.mindsetworks.com/science/",
//     level: 2,
//     type: "PDF",
//     createdBy: {
//       email: "laura.white@example.com",
//       avatar: "https://i.pravatar.cc/300?img=8",
//       username: "Dr. Laura White",
//       name: "Laura White",
//       city: "San Francisco",
//       id: 2,
//       jobTitle: "Psychologist and Educator",
//       country: "USA",
//       level: 7,
//     },
//     createdAt: new Date("2023-11-05"),
//     tags: ["Growth Mindset", "Psychology", "Education"],
//   },
//   {
//     id: 3,
//     title: "Project-Based Learning in STEAM",
//     description:
//       "Explore project-based learning strategies for effective STEAM education.",
//     link: "https://www.pblworks.org/what-is-pbl",
//     level: 3,
//     type: "Webinar",
//     createdBy: {
//       name: "Sarah Thompson",
//       email: "sarah.thompson@example.com",
//       avatar: "https://i.pravatar.cc/300?img=7",
//       username: "Sarah Thompson",
//       city: "New York",
//       id: 3,
//       jobTitle: "Educational Consultant",
//       country: "USA",
//       level: 6,
//     },
//     createdAt: new Date("2023-12-15"),
//     tags: ["STEAM", "Project-Based Learning", "Webinar"],
//   },
//   {
//     id: 4,
//     title: "Using Technology to Enhance Experiential Learning",
//     description:
//       "Learn how to incorporate technology into experiential learning practices.",
//     link: "https://edtechmagazine.com/k12/article/2021/02/4-ways-technology-enhances-experiential-learning",
//     level: 4,
//     type: "Article",
//     createdBy: {
//       email: "michael.lee@example.com",
//       name: "Michael Lee",
//       avatar: "https://i.pravatar.cc/300?img=6",
//       username: "Michael Lee",
//       city: "Chicago",
//       id: 4,
//       jobTitle: "EdTech Specialist",
//       country: "USA",
//       level: 4,
//     },
//     createdAt: new Date("2023-10-20"),
//     tags: ["Experiential Learning", "Technology", "EdTech"],
//   },
//   {
//     id: 5,
//     title: "Interactive STEAM Tools for Educators",
//     description:
//       "Discover interactive tools that can be used to enhance STEAM education.",
//     link: "https://www.edutopia.org/article/interactive-tools-enhance-steam-education",
//     level: 3,
//     type: "Tool",
//     createdBy: {
//       email: "robert.brown@example.com",
//       name: "Robert Brown",
//       avatar: "https://i.pravatar.cc/300?img=4",
//       username: "Robert Brown",
//       city: "Austin",
//       id: 5,
//       jobTitle: "STEAM Education Advocate",
//       country: "USA",
//       level: 5,
//     },
//     createdAt: new Date("2023-09-30"),
//     tags: ["STEAM", "Tools", "Interactive"],
//   },
//   {
//     id: 6,
//     title: "Case Studies in STEAM Implementation",
//     description: "Real-world examples of successful STEAM programs in schools.",
//     link: "https://www.steameducation.org/case-studies",
//     level: 2,
//     type: "Case Study",
//     createdBy: {
//       email: "emily.carter@example.com",
//       avatar: "https://i.pravatar.cc/300?img=5",
//       username: "Dr. Emily Carter",
//       name: "Emily Carter",
//       city: "Boston",
//       id: 6,
//       jobTitle: "STEAM Curriculum Developer",
//       country: "USA",
//       level: 5,
//     },
//     createdAt: new Date("2023-08-12"),
//     tags: ["STEAM", "Case Study", "Education"],
//   },
//   {
//     id: 7,
//     title: "Building Resilience through a Growth Mindset",
//     description:
//       "Strategies for fostering resilience in students by promoting a growth mindset.",
//     link: "https://www.resilienteducator.com/classroom-resources/growth-mindset/",
//     level: 4,
//     type: "Blog Post",
//     createdBy: {
//       email: "laura.white@example.com",
//       avatar: "https://i.pravatar.cc/300?img=8",
//       name: "Laura White",
//       username: "Dr. Laura White",
//       city: "San Francisco",
//       id: 7,
//       jobTitle: "Psychologist and Educator",
//       country: "USA",
//       level: 7,
//     },
//     createdAt: new Date("2024-02-01"),
//     tags: ["Growth Mindset", "Resilience", "Education"],
//   },
//   {
//     id: 8,
//     title: "The Role of Arts in STEAM Education",
//     description:
//       "Understanding the critical role of arts in a comprehensive STEAM curriculum.",
//     link: "https://www.edutopia.org/article/role-arts-steam-education",
//     level: 3,
//     type: "Article",
//     createdBy: {
//       email: "michael.lee@example.com",
//       name: "Michael Lee",
//       avatar: "https://i.pravatar.cc/300?img=6",
//       username: "Michael Lee",
//       city: "Chicago",
//       id: 9,
//       jobTitle: "EdTech Specialist",
//       country: "USA",
//       level: 4,
//     },
//     createdAt: new Date("2023-11-25"),
//     tags: ["STEAM", "Arts", "Education"],
//   },
//   {
//     id: 9,
//     title: "Effective Assessment in STEAM Education",
//     description:
//       "Guidelines for assessing student progress and outcomes in STEAM projects.",
//     link: "https://www.steameducation.org/assessment",
//     level: 2,
//     type: "Guide",
//     createdBy: {
//       email: "sarah.thompson@example.com",
//       avatar: "https://i.pravatar.cc/300?img=7",
//       name: "Sarah Thompson",
//       username: "Sarah Thompson",
//       city: "New York",
//       id: 11,
//       jobTitle: "Educational Consultant",
//       country: "USA",
//       level: 6,
//     },
//     createdAt: new Date("2023-10-05"),
//     tags: ["STEAM", "Assessment", "Education"],
//   },
//   {
//     id: 10,
//     title: "Creating a Growth Mindset Culture",
//     description:
//       "Learn how to create a classroom culture that supports and nurtures a growth mindset.",
//     link: "https://www.mindsetworks.com/science/Creating-a-Growth-Mindset-Culture",
//     level: 5,
//     type: "Video",
//     createdBy: {
//       email: "laura.white@example.com",
//       avatar: "https://i.pravatar.cc/300?img=8",
//       username: "Dr. Laura White",
//       city: "San Francisco",
//       name: "Laura White",
//       id: 2,
//       jobTitle: "Psychologist and Educator",
//       country: "USA",
//       level: 7,
//     },
//     createdAt: new Date("2023-12-02"),
//     tags: ["Growth Mindset", "Classroom Culture", "Education"],
//   },
//   {
//     id: 11,
//     title: "Interactive STEAM Project Workbook",
//     description:
//       "Download this workbook to guide your students through hands-on STEAM projects.",
//     link: "https://www.steameducation.org/interactive-steam-workbook.pdf",
//     level: 4,
//     type: "PDF",
//     createdBy: {
//       email: "robert.brown@example.com",
//       name: "Robert Brown",
//       avatar: "https://i.pravatar.cc/300?img=4",
//       username: "Robert Brown",
//       city: "Austin",
//       id: 2,
//       jobTitle: "STEAM Education Advocate",
//       country: "USA",
//       level: 5,
//     },
//     createdAt: new Date("2023-11-10"),
//     tags: ["STEAM", "Workbook", "PDF"],
//   },
//   {
//     id: 12,
//     title: "Creative STEAM Challenges",
//     description:
//       "A collection of creative STEAM challenges that can be adapted for any age group.",
//     link: "https://www.creativechallenges.org/steam",
//     level: 3,
//     type: "Other",
//     createdBy: {
//       email: "emily.carter@example.com",
//       avatar: "https://i.pravatar.cc/300?img=5",
//       username: "Dr. Emily Carter",
//       name: "Emily Carter",
//       city: "Boston",
//       id: 3,
//       jobTitle: "STEAM Curriculum Developer",
//       country: "USA",
//       level: 5,
//     },
//     createdAt: new Date("2024-01-20"),
//     tags: ["STEAM", "Challenges", "Creative"],
//   },
// ];
