// import { IUser } from "@/typings/course";

// export const mockUserList: IUser[] = [
//   {
//     email: "emily.carter@example.com",
//     avatar: "https://i.pravatar.cc/300?img=5",
//     username: "Dr. Emily Carter",
//     interests: ["STEAM Education", "Curriculum Development"],
//     city: "Zagreb",
//     id: 1,
//     name: "Emily Carter",
//     jobTitle: "STEAM Curriculum Developer",
//     bio: "An education specialist with a focus on integrating STEAM methodologies into the classroom. Passionate about hands-on learning and technology in education.",
//     country: "Croatia",
//     isNetworking: true,
//     website: "https://emilycarteredu.com",
//     linkedin: "https://www.linkedin.com/in/emilycarter",
//     twitter: "https://twitter.com/emilycarteredu",
//     availabilityStatus: "Available for consulting",
//     activityLevel: 85,
//     experiencePoints: 1500,
//     level: 5,
//     connectionsCount: 250,
//     isMentor: true,
//     expertise: ["STEAM", "Project-Based Learning"],
//     mentees: [],
//   },
//   {
//     email: "michael.lee@example.com",
//     avatar: "https://i.pravatar.cc/300?img=18",
//     username: "Michael Lee",
//     name: "Michael Lee",
//     interests: ["EdTech", "STEAM", "Creative Arts", "Technology Integration"],
//     city: "Split",
//     id: 2,
//     jobTitle: "EdTech Specialist",
//     bio: "An EdTech enthusiast with a passion for using technology to enhance learning experiences. I specialize in integrating creative arts into STEM education.",
//     country: "Croatia",
//     isNetworking: true,
//     linkedin: "https://www.linkedin.com/in/michaellee",
//     twitter: "https://twitter.com/michaelleetech",
//     availabilityStatus: "Open to networking",
//     activityLevel: 70,
//     experiencePoints: 1200,
//     level: 4,
//     connectionsCount: 180,
//     isMentor: false,
//     expertise: ["EdTech", "STEAM", "Creative Arts"],
//     mentees: [],
//   },
//   {
//     email: "sarah.thompson@example.com",
//     avatar: "https://i.pravatar.cc/300?img=51",
//     name: "Sarah Thompson",
//     username: "Sarah Thompson",
//     interests: ["Experiential Learning", "Mentorship"],
//     city: "Rijeka",
//     id: 3,
//     jobTitle: "Educational Consultant",
//     bio: "With over 15 years of experience in educational consulting, I help schools implement effective project-based learning strategies and mentor new educators.",
//     country: "Croatia",
//     isNetworking: false,
//     linkedin: "https://www.linkedin.com/in/sarahthompson",
//     availabilityStatus: "Currently mentoring",
//     activityLevel: 90,
//     experiencePoints: 2000,
//     level: 6,
//     connectionsCount: 300,
//     isMentor: true,
//     expertise: [
//       "Project-Based Learning",
//       "Experiential Learning",
//       "Mentorship",
//     ],
//     mentees: [
//       {
//         email: "jane.doe@example.com",
//         avatar: "https://i.pravatar.cc/300?img=15",
//         username: "Jane Doe",
//         city: "Dubrovnik",
//         id: 4,
//         name: "Jane Doe",
//         jobTitle: "Junior Educator",
//         country: "Croatia",
//         level: 2,
//       },
//     ],
//   },
//   {
//     email: "robert.brown@example.com",
//     avatar: "https://i.pravatar.cc/300?img=8",
//     username: "Robert Brown",
//     interests: ["Arts Integration", "Interactive Learning"],
//     city: "Osijek",
//     id: 11,
//     name: "Robert Brown",
//     jobTitle: "STEAM Education Advocate",
//     bio: "A strong advocate for the integration of arts in STEM, aiming to create a more inclusive and creative learning environment for students of all backgrounds.",
//     country: "Croatia",
//     isNetworking: true,
//     linkedin: "https://www.linkedin.com/in/robertbrown",
//     twitter: "https://twitter.com/robertbrownedu",
//     instagram: "https://instagram.com/robertbrownedu",
//     availabilityStatus: "Available for speaking engagements",
//     activityLevel: 65,
//     experiencePoints: 1100,
//     level: 5,
//     connectionsCount: 220,
//     isMentor: false,
//     expertise: ["STEAM", "Arts Integration", "Interactive Learning"],
//     mentees: [],
//   },
//   {
//     email: "laura.white@example.com",
//     avatar: "https://i.pravatar.cc/300?img=44",
//     name: "Laura White",
//     username: "Dr. Laura White",
//     interests: ["Psychology", "Growth Mindset", "Educational Psychology"],
//     city: "Zadar",
//     id: 5,
//     jobTitle: "Psychologist and Educator",
//     bio: "Psychologist specializing in mindset theory and its applications in education. I work to help educators foster growth mindsets in their students.",
//     country: "Croatia",
//     isNetworking: true,
//     website: "https://laurawhitemindset.com",
//     linkedin: "https://www.linkedin.com/in/laurawhite",
//     twitter: "https://twitter.com/laurawhitephd",
//     availabilityStatus: "Open to collaborations",
//     activityLevel: 95,
//     experiencePoints: 2500,
//     level: 7,
//     connectionsCount: 350,
//     isMentor: true,
//     expertise: ["Psychology", "Growth Mindset", "Educational Psychology"],
//     mentees: [
//       {
//         email: "alice.johnson@example.com",
//         avatar: "https://i.pravatar.cc/300?img=3",
//         username: "Alice Johnson",
//         name: "Alice Johnson",
//         city: "Pula",
//         id: 6,
//         jobTitle: "Graduate Student",
//         country: "Croatia",
//         level: 3,
//       },
//     ],
//   },
// ];
